spring:
   application:
      name: brunopay
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/brunopay
      username: postgres
      password: mayaralinda123
      initialization-mode: always
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      format_sql: true